name: Build and Deploy

# workflow triggers
on:
    push:
        branches:
            - master

    workflow_dispatch:

    # Allows external webhook trigger
    repository_dispatch:
        types:
            - webhook

# build process
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '20'
            - run: npm install
            - run: npm run build
            - name: Upload Build Result
              uses: actions/upload-artifact@v2
              with:
                  name: sb-build
                  path: public
                  retention-days: 1

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download Build Result
              uses: actions/download-artifact@v2
              with:
                  name: sb-build
                  path: build
            - name: Upload ftp
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              with:
                  server: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  password: ${{ secrets.PASS }}
                  protocol: ftps
                  local-dir: 'build/'
                  server-dir: 'public_html/shelleybassett.com/'
